# Generated by Django 3.0.8 on 2020-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='fact',
        ),
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.CharField(default='empty', max_length=1000),
            preserve_default=False,
        ),
    ]
